"""add shipping charge to orders

Revision ID: 046d65f83365
Revises: 879a441669c1
Create Date: 2026-08-23 16:34:25.995170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046d65f83365'
down_revision = '879a441669c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'shipping_charge',
                sa.Float(),
                nullable=False,
                server_default='0'
            )
        ) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_charge')

    # ### end Alembic commands ###
