"""add packaging fields to product

Revision ID: 1c543430d9e3
Revises: fa001b44566e
Create Date: 2026-08-23 17:46:23.600332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c543430d9e3'
down_revision = 'fa001b44566e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('package_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('package_breadth', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('package_height', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('package_height')
        batch_op.drop_column('package_breadth')
        batch_op.drop_column('package_length')
        batch_op.drop_column('package_weight')

    # ### end Alembic commands ###
