"""Add orders table

Revision ID: 47e540bca9d2
Revises: 5c8cf570cbde
Create Date: 2026-08-10 18:22:09.369587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e540bca9d2'
down_revision = '5c8cf570cbde'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('order', schema=None) as batch_op:

        batch_op.add_column(
            sa.Column(
                'user_id',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'product_id',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'price',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'total_amount',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'address',
                sa.String(length=255),
                nullable=True
            )
        )

        batch_op.create_foreign_key(
            None,
            'user',
            ['user_id'],
            ['id']
        )

        batch_op.create_foreign_key(
            None,
            'product',
            ['product_id'],
            ['id']
        )
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('address')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('price')
        batch_op.drop_column('product_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
