"""add terms acceptance fields

Revision ID: 879a441669c1
Revises: de9d6ae1cbd7
Create Date: 2026-08-23 16:10:14.753850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879a441669c1'
down_revision = 'de9d6ae1cbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('terms_accepted_at')
        batch_op.drop_column('terms_accepted')

    # ### end Alembic commands ###
