"""add refund processing and refunded timestamps

Revision ID: 99320f8ee135
Revises: bc7a068f4335
Create Date: 2026-08-23 01:25:21.334521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99320f8ee135'
down_revision = 'bc7a068f4335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refund_processing_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('refunded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('refunded_at')
        batch_op.drop_column('refund_processing_at')

    # ### end Alembic commands ###
