"""add individual order status timestamps

Revision ID: de9d6ae1cbd7
Revises: 99320f8ee135
Create Date: 2026-08-23 02:12:25.899355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9d6ae1cbd7'
down_revision = '99320f8ee135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_verification_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pending_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('packed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('shipped_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('shipped_at')
        batch_op.drop_column('packed_at')
        batch_op.drop_column('pending_at')
        batch_op.drop_column('payment_verification_at')

    # ### end Alembic commands ###
