"""add packaging profile to products

Revision ID: fa001b44566e
Revises: 046d65f83365
Create Date: 2026-08-23 17:25:28.807764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa001b44566e'
down_revision = '046d65f83365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packaging_profile', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('packaging_profile')

    # ### end Alembic commands ###
